### ISSUE TITLE
请问脚本中的参数和我实际抓到的不一样影响使用吗

### ISSUE THREAD

**Issue by wzcsimon123** [Misaka-Aki/BUCT_Report#1]
我自己抓包抓到的和脚本里的不一样
比如说经纬度，脚本里用O,P表示，而我抓到的用的是Q，R

还有一些参数比如说id,uid,date,created或者是addressComponent是可以不填吗

**Comment by Misaka-Aki** [comment]
需要你抓取的只有企业微信的UUKEY和eai-sess的值，用于身份验证，详情可以去readme里原作者仓库看看：https://github.com/W0n9/BUCT_COVID-19_Report

具体我不太懂（毕竟我不是学计算机的），但是原脚本里面，这个经纬度是作者定的，并非学校地址，用于在未指定地址时“把你带到一个安全的位置”（应该是这样的）。

因此需要自定义的参数，仅有省市地址那四个，通过环境变量输入。

**Comment by wzcsimon123** [comment]
原作者的代码已经比较久了，现在打卡的信息应该变了点。
这是我找到的一些变化
新增
```python
"ismoved":"0",  # 与上次地点是否有不同
"sfxk":"0",     #未知
"sjjcwhry":"0", # 是否接触武汉人员 否
"sjjchbry":"0", # 是否接触湖北人员 否
"sjtjhb":"0",   # 是否途径湖北 否
"sftjwh":"0",   # 是否途径武汉 否
"sfsfbh":"0",   #未知
"sfygtjzzfj":"0",#未知
"uid":"   ",
"id":"    ",
"created":   #创建时间
"date": #时间
    
```

在`geo_api_info #伽利略定位系统详情`中

原代码

```python
 'position': {
            'O': 113.0270592,  # 经度
            'P': 22.5524345,  # 纬度
            'lng': 113.0270592,  # 经度
            'lat': 22.5524345  # 纬度
        },
```

抓包打卡时实际发送的表单

```python
"location": {
                "Q": 40.xxxxx,
                "R": 116.xxxxx,
                "lng": 116.xxxxx,
                "lat": 40.xxxxx
            }
```

**Comment by Misaka-Aki** [comment]
我好久没管过了，一直也没报错，说明可能系统并不会核实上报的信息。

这些改动我可以尝试加进去。

**Comment by Misaka-Aki** [comment]
> 原作者的代码已经比较久了，现在打卡的信息应该变了点。 这是我找到的一些变化 新增
> 
> ```python
> "ismoved":"0",  # 与上次地点是否有不同
> "sfxk":"0",     #未知
> "sjjcwhry":"0", # 是否接触武汉人员 否
> "sjjchbry":"0", # 是否接触湖北人员 否
> "sjtjhb":"0",   # 是否途径湖北 否
> "sftjwh":"0",   # 是否途径武汉 否
> "sfsfbh":"0",   #未知
> "sfygtjzzfj":"0",#未知
> "uid":"   ",
> "id":"    ",
> "created":   #创建时间
> "date": #时间
>     
> ```
> 
> 在`geo_api_info #伽利略定位系统详情`中
> 
> 原代码
> 
> ```python
>  'position': {
>             'O': 113.0270592,  # 经度
>             'P': 22.5524345,  # 纬度
>             'lng': 113.0270592,  # 经度
>             'lat': 22.5524345  # 纬度
>         },
> ```
> 
> 抓包打卡时实际发送的表单
> 
> ```python
> "location": {
>                 "Q": 40.xxxxx,
>                 "R": 116.xxxxx,
>                 "lng": 116.xxxxx,
>                 "lat": 40.xxxxx
>             }
> ```

这段新增信息中的数据并未在实际打卡页面中展示，且与武汉有关，疑似为2020年的老旧信息。
目前还能用，所以决定先不改。

**Comment by Misaka-Aki** [comment]
经纬度在修改为40.xxx格式后报错，非十进制。

**Comment by wzcsimon123** [comment]
> 经纬度在修改为40.xxx格式后报错，非十进制。

xx是因为我不想暴露实际位置，填的时候还是要填真实的地址。
还有`
"uid":"   ",
"id":"    ",
`
实际上也是有值的，不过跟个人信息有关，我也没有写。

主要的问题是经纬度，如果经纬度在打卡中起了作用，就会打到国外去，如果只是为了获取`'area'`等字段就没有问题

以下信息我没有使用也能打卡成功。

`"created":  ` 的值应该为`str(int(time.time()))`
`'date'` 的值应该为str(datetime.date.today() - datetime.timedelta(days=1)).replace("-", "")

**Comment by Misaka-Aki** [comment]
> > 经纬度在修改为40.xxx格式后报错，非十进制。
> 
> xx是因为我不想暴露实际位置，填的时候还是要填真实的地址。 还有`"uid":" ", "id":" ",` 实际上也是有值的，不过跟个人信息有关，我也没有写。
> 
> 以下信息我没有使用也能打卡成功。
> 
> `"created": ` 的值应该为`str(int(time.time()))` `'date'` 的值应该为str(datetime.date.today() - datetime.timedelta(days=1)).replace("-", "")

能用就行，反正没人管内容，省事儿最重要。
